"""Add photo

Revision ID: b3c8bdb423f9
Revises: 0c26d84d3e2f
Create Date: 2025-06-18 09:12:36.267672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c8bdb423f9'
down_revision = '0c26d84d3e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patronymic', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patronymic')

    # ### end Alembic commands ###
