"""edit photo

Revision ID: eaf637862d67
Revises: b3c8bdb423f9
Create Date: 2025-06-18 09:15:44.993306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf637862d67'
down_revision = 'b3c8bdb423f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('patronymic',
               existing_type=sa.DATE(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('patronymic',
               existing_type=sa.String(length=64),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
